name: OpenWRT Github CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Copiler
      run: |
        df -h / > log.txt

    - name: Upload To Releases
      uses: softprops/action-gh-release@v1
      if: env.UPLOADTORELEASE == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Log, ${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        files: log.txt
