name: OpenWRT Github CI
on: [push]

env:
  web: 'google.com'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Start SSH via tmate
      uses: P3TERX/ssh2actions@main
